### ISSUE TITLE
Problem with network configuration 

### ISSUE THREAD

**Issue by Obi8** [fedberry/fedberry#20] opened 2016-03-26 20:28 UTC
There is a problem with the network configuration in fedberry-xfce-23.2-test1.raw with raspberry pi 3.

Problem:
In the GUI installer i configurated the WLAN connection and the hostname and then i can't go back to the main menu, where i can create a user, set timezone and so on.

**Comment by agrez** [comment] 2016-03-29 11:58
Thanks for the bug report. Yes, I can confirm this. Looks like initial-setup has a bug. Will have to investigate when I get some time.

**Comment by mrjoshuap** [comment] 2016-06-01 05:37
is this in fedberry-config?

**Comment by agrez** [comment] 2016-06-01 13:46
Its a bug somewhere in initial-setup or initial-setup-gui
https://github.com/rhinstaller/initial-setup

I was thinking we need to update to the latest release and see if its fixed but I just haven't had time to do this yet.

**Comment by agrez** [comment] 2016-10-29 00:21
ok, as this is really the only bug that is preventing us going for 24.1 final, I thought I'd better revisit it.

I managed to get a backtrace, which is a good start:

__init__.py:1241:restartThread:AttributeError: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
File "/usr/lib/python3.5/site-packages/pyanaconda/ui/gui/spokes/network.py", line 1551, in on_back_clicked
NormalSpoke.on_back_clicked(self, button)
File "/usr/lib/python3.5/site-packages/pyanaconda/ui/gui/spokes/__init__.py", line 76, in on_back_clicked
self.main_window.current_action.spoke_done(self)
File "/usr/lib/python3.5/site-packages/pyanaconda/ui/gui/hubs/__init__.py", line 396, in spoke_done
spoke.apply()
File "/usr/lib/python3.5/site-packages/pyanaconda/ui/gui/spokes/network.py", line 1480, in apply
payloadMgr.restartThread(self.storage, self.data, self.payload, self.instclass, checkmount=False)
File "/usr/lib/python3.5/site-packages/pyanaconda/packaging/__init__.py", line 1241, in restartThread
if threadMgr.get(THREAD_PAYLOAD_RESTART):
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by agrez** [comment] 2016-10-29 00:26
Seems there is also a bug report for this exact problem upstream:  https://bugzilla.redhat.com/show_bug.cgi?id=1367882

Different hardware, but same bug.

**Comment by agrez** [comment] 2017-07-13 08:26
Closing this bug as I can't reproduce this in our 25.1 releases

**Closed by agrez** 2017-07-13 08:26 UTC
Labels: bug
