### ISSUE TITLE
filesystem resize fails on 64GB SD cards

### ISSUE THREAD

**Issue by mrjoshuap** [fedberry/fedberry#8] opened 2016-02-22 19:07 UTC
Please note that I did not test this on cards greater than 64GB, though I suspect they also have issues.

I have several different microSD cards:

32GB Micro Center microSDXC
32GB Samsung microSDXC UHS-I
32GB SanDisk microSDXC

64GB Micro Center microSDXC
64GB Samsung microSDXC UHS-I
64GB SanDisk microSDXC

After flashing these cards with the latest FedBerry minimal image (fedora-23-remix-rpi2-minimal-1.raw), all booted the first time successfully.  All 32GB and smaller were resized and rebooted properly.  The subsequent reboot after filesystem resizing failed on all the 64GB microSD cards, regardless of make and manufacturer; each card was re-imaged 2 times.

The error after the initial reboot is:

```
PANIC: VFS: Unable to mount root fs on unknown-block(179,3)
```

See attached images.

I have been able to work around this problem by resizing the filesystem on my desktop using gparted and then booting off of it in the RPi2.

![img_3496](https://cloud.githubusercontent.com/assets/5722442/13229039/f3bc6eae-d96c-11e5-944e-5b1fa79f5973.JPG)
![img_3495](https://cloud.githubusercontent.com/assets/5722442/13229041/f668a154-d96c-11e5-90cb-e0e4de18fc8b.JPG)
![img_3497](https://cloud.githubusercontent.com/assets/5722442/13229036/ec5b93d8-d96c-11e5-8bec-177e97ad1b1f.JPG)

**Comment by mrjoshuap** [comment] 2016-02-22 19:27
I can confirm the same problem affects the XFCE image: fedora-23-remix-rpi2-xfce-1-raw

Same as before, if I resize the image before using it in the RPi2, it works perfectly.

**Comment by agrez** [comment] 2016-02-23 01:23
Thanks for reporting this Josh. I don't have a 64GB (or bigger) sd card so I haven't yet hit this bug. I will grab one today and see if I can make some headway on this issue. Thus far, I have shifted my rootfs onto external usb HD's when I require extra space for compiling / building etc etc).

I would be surprised if the problem lies in the Fedora's rootfs-resize scripts otherwise I'm sure people would have reported this already but I guess I will have to start there and work my way down the chain until I hit the bcm2835-sdhost (mmc) kernel driver.

**Comment by agrez** [comment] 2016-02-24 03:11
OK, I can reproduce this issue with the 64GB micro sd card I just bought. At first glance there does seem to be a problem with the rootfs-resize/pyparted/libparted stack.

I start seeing problems when rootfs-resize calls the getMaxGeometry() (pyparted function in 'Partition' class) and it returns an incorrect end geometry value for the partition. I would have expect this value would be approximately (exactly?) the 'maxSize' returned from optimalAlignedConstraint() but alas, its not (98703359 vs 124735488 sectors).

```
print root.getMaxGeometry(constraint).end
98703359
```

```
print constraint
parted.Constraint instance --
  startAlign: <parted.alignment.Alignment object at 0x744d4c10>  endAlign: <parted.alignment.Alignment object at 0x744d4bf0>
  startRange: <parted.geometry.Geometry object at 0x744d4cd0>  endRange: <parted.geometry.Geometry object at 0x744d4cf0>
  minSize: 1  maxSize: 124735488
  PedConstraint: <_ped.Constraint object at 0x744e1308>
```

Other arguments passed to setPartitionGeometry() seem ok.

```
print root.geometry.end
4884479
print root.geometry.start
2541568
```

**Comment by Gormartsen** [comment] 2016-02-24 03:39
It looks to me like int overflow.


Regards,
Gor Martsen
@gormartsen

**Comment by agrez** [comment] 2016-02-24 05:48
I suppose we need to file a bug report somewhere then (not sure if I should go via bugzilla or liaise directly with the developers first (the project now uses github). https://github.com/rhinstaller/pyparted

I forgot to add my before and after snapshots of the partition carnage in my last comment. See attached txt files.
[before_rootfs_resize.txt](https://github.com/fedberry/fedberry/files/143997/before_rootfs_resize.txt)
[after_rootsfs_resize.txt](https://github.com/fedberry/fedberry/files/143998/after_rootsfs_resize.txt)

**Comment by agrez** [comment] 2016-02-24 06:38
We also better document a temporary workaround (until we release some updated images) for installing onto sd cards that are >= 64GB. This will need to be done for all our releases that automatically resize after the initial boot (ie. all of them except for 'mini').

Once 'dd' finishes writing to the sd card:

* mount '/' on sdcard and as root user:

`rm -f /.rootfs-repartition`

**OR**

* mount /boot partition and open cmdline.txt in your favourite text editor add `nofsresize` to the kernel cmd line.

Either of these options will disable automatic re-sizing at boot time. You will then have to manually resize your rootfs at a later stage (In the past I have used fdisk to do this job with no issues).

**Comment by dshesq00x** [comment] 2016-03-03 14:03
Thanks to all for your work on this:  This is a little off topic, but If you are seeking more storage on the Pi, I was able to use a  ($21.98) Sisun USB 3.0 Super Speed SATA III Lay-Flat Hard Drive Docking Station with 2 USB Charging Hub (ASMedia ASM1053E SATA III to USB Chipset, UASP and 6TB HDD).  The dock will hold a hard drive, and power the Pi as well.  The micro-SD is just a boot loader and all of the activity gets handled by the hard drive.  I installed Pidora, used fdisk to create a petition on the drive.  Format the drive [mke2fs -t ext4 -L rootfs /dev/sda1] then mount the drive [mount /dev/sda1 /mnt] rsync the root files to the drive [rsync -axv / /mnt] change the /boot/cmdline.txt to [dwc_otg.lpm_enable=0 console=ttyAMA0,115200 kgdboc=ttyAMA0,115200 console=tty1 root=/dev/sda1 ro rootfstype=ext4 rootwait quiet rootdelay=5]  no change was needed in the /mnt/etc/fstab file.  reboot the system, and I get. 
[-------@pidora ~]$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root       688G  3.2G  650G   1% /
devtmpfs        218M     0  218M   0% /dev
tmpfs           218M     0  218M   0% /dev/shm
tmpfs           218M  360K  218M   1% /run
tmpfs           218M     0  218M   0% /sys/fs/cgroup
tmpfs           218M     0  218M   0% /tmp
/dev/mmcblk0p1   50M   23M   28M  45% /boot
I was then able to rsync files onto the Pi from another computer on my home network, and connect to the Pi using the "Connect to Server" in Ubuntu files (Places) with sftp://{username}@pidora/home/{username}
One might be able to use a "usb card reader" to format a micro-SD card and transfer the system to the larger card on the reader, then shutdown and put the larger card in the PI and reboot

**Comment by agrez** [comment] 2016-03-04 00:25
BTW, I'm working on a fix for this issue. Will most likely add our own partition resizing support into fedberry-config as a workaround. Whether its a temporary solution or a permanent fix remains to be seen.

**Comment by mrjoshuap** [comment] 2016-03-04 00:58
@agrez created BZ 1314587 for this issue as no response in a week on https://github.com/rhinstaller/pyparted/issues/25

https://bugzilla.redhat.com/show_bug.cgi?id=1314587

**Comment by agrez** [comment] 2016-03-04 13:09
Most likely Murphy's Law is to blame. These issues only happen just after you leave on your well earned holiday. He's most probably sitting on a beach somewhere, listening to some tunes, enjoying a nice cold one, blissfully unaware of the bug :-)

**Comment by agrez** [comment] 2016-03-14 14:28
This is issue is fixed in our new test releases but I won't close the issue just yet. I would like to actually know what is going on with pyparted parted at some point and having this issue around will remind me.

**Comment by dcantrell** [comment] 2016-03-16 20:44
Hey guys, pyparted owner here.  I have a message sitting in my inbox pointing me to this bug report and I responded saying I would look in to it, but finding time has been challenging.  I am looking in to this now and hopefully can report back something from my end of things relatively soon.  I did go out and buy a 64GB card so I can try to recreate the problem locally.  If anyone has any specific brand recommendations that I should look in to, let me know.

**Comment by agrez** [comment] 2016-03-17 00:48
Hi David
Thanks again for looking into this. I reproduced the issue on a 64GB SanDisk Extreme microSDXC. I tend to stick with SanDisk SD cards as they are common and known to work with RPi's (RPi's have a history of being a bit fussy at times when it comes to SD cards).
http://elinux.org/RPi_SD_cards

**Comment by dcantrell** [comment] 2016-03-17 15:48
The problem is in libparted.  I have posted a candidate patch for parted to fix this problem:

[https://dcantrel.fedorapeople.org/patches/parted/0001-Use-BLKSSZGET-to-get-device-sector-size-in-_device_p.patch](url)

You can take that patch and add it to the parted SRPM in Fedora, rebuild it, and upgrade your parted and parted-devel packages locally.  You do not need to change pyparted.  If you can install an updated parted with this patch, see if it resolves the problem originally reported.

**Comment by agrez** [comment] 2016-03-18 00:32
Ok, updated / patched parted rpms are now available in unstable for testing. I will get time to test this out either tonight or tomorrow at some point. Thanks David.

**Comment by mrjoshuap** [comment] 2016-06-01 05:44
I'll re-run and verify this ASAP.

**Comment by agrez** [comment] 2016-06-01 13:39
We should close this bug as we have had our own solution (using fedberry-config) in place for quite some time now and it seems to be working well. However with my testing, even with this patch parted is still problematic with =>64GB cards. Currently. People should stick to using fdisk when partitioning SDXC cards.

**Closed** 2017-01-19 14:06 UTC
Labels: bug
